import pandas as pd
import numpy as np

df=pd.read_csv('data/projectdata/report3_5.csv')

In [7]:
df.columns

Index(['Country', 'Year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'depressive disorders', 'schooling',
       'alcohol disorders', 'suicide rates', 'Obesity'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1897 entries, 0 to 1896
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Country                           1897 non-null   object 
 1   Year                              1897 non-null   int64  
 2   Life Ladder                       1897 non-null   float64
 3   Log GDP per capita                1897 non-null   float64
 4   Social support                    1897 non-null   float64
 5   Healthy life expectancy at birth  1897 non-null   float64
 6   Freedom to make life choices      1897 non-null   float64
 7   Generosity                        1897 non-null   float64
 8   Perceptions of corruption         1897 non-null   float64
 9   depressive disorders              1897 non-null   float64
 10  schooling                         1897 non-null   float64
 11  alcohol disorders                 1897 non-null   float64
 12  suicid

In [9]:
#나라이름 원핫인코딩
one_c=pd.get_dummies(df['Country'])
one_c.head()

Afghanistan  Albania  Algeria  Angola  Argentina  Armenia  Australia  \
0            1        0        0       0          0        0          0   
1            1        0        0       0          0        0          0   
2            1        0        0       0          0        0          0   
3            1        0        0       0          0        0          0   
4            1        0        0       0          0        0          0   

   Austria  Azerbaijan  Bahrain  ...  United Arab Emirates  United Kingdom  \
0        0           0        0  ...                     0               0   
1        0           0        0  ...                     0               0   
2        0           0        0  ...                     0               0   
3        0           0        0  ...                     0               0   
4        0           0        0  ...                     0               0   

   United States  Uruguay  Uzbekistan  Venezuela  Vietnam  Yemen  Zambia  \
0              0        0           0          0        0      0       0   
1              0        0           0          0        0      0       0   
2              0        0           0          0        0      0       0   
3              0        0           0          0        0      0       0   
4              0        0           0          0        0      0       0   

   Zimbabwe  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 160 columns]

In [10]:
#합치기 
ndf=pd.concat([df,one_c],axis=1)
ndf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1897 entries, 0 to 1896
Columns: 174 entries, Country to Zimbabwe
dtypes: float64(12), int64(1), object(1), uint8(160)
memory usage: 504.0+ KB


In [12]:
pd.set_option('display.width',None)      # 출력화면의 너비
pd.set_option('display.max_rows',None)    # 출력할 행의 개수 한도
pd.set_option('display.max_columns',None)  # 출력할 열의 개수 한도
pd.set_option('display.max_colwidth',20) # 출력할 열의 너비


In [13]:
# 행복지수로 내림차순 
ndf.sort_values(by='Life Ladder', ascending=False,inplace=True)

In [14]:
# 인덱스 재정렬
ndf.reset_index(drop=True, inplace=True)  
ndf.head()

Country  Year  Life Ladder  Log GDP per capita  Social support  \
0  Denmark  2005        8.019              10.851           0.972   
1  Denmark  2008        7.971              10.880           0.954   
2  Finland  2020        7.889              10.750           0.962   
3  Finland  2018        7.858              10.783           0.962   
4  Denmark  2007        7.834              10.891           0.954   

   Healthy life expectancy at birth  Freedom to make life choices  Generosity  \
0                69.60                             0.971               -0.127   
1                70.08                             0.970                0.272   
2                72.10                             0.962               -0.116   
3                71.90                             0.938               -0.127   
4                69.92                             0.932                0.240   

   Perceptions of corruption  depressive disorders  schooling  \
0                0.237              196175.189255        12.8   
1                0.248              195682.481706        12.9   
2                0.164              261800.122400        12.4   
3                0.199              256472.440500        12.4   
4                0.206              195599.296492        12.5   

   alcohol disorders  suicide rates  Obesity  Afghanistan  Albania  Algeria  \
0           9.966839       1.385229     7.60            0        0        0   
1          10.426470       1.365589     7.58            0        0        0   
2           6.979488       1.576410    10.93            0        0        0   
3           6.979488       1.576410    10.93            0        0        0   
4          10.896428       1.385044     7.62            0        0        0   

   Angola  Argentina  Armenia  Australia  Austria  Azerbaijan  Bahrain  \
0       0          0        0          0        0           0        0   
1       0          0        0          0        0           0        0   
2       0          0        0          0        0           0        0   
3       0          0        0          0        0           0        0   
4       0          0        0          0        0           0        0   

   Bangladesh  Belarus  Belgium  Belize  Benin  Bhutan  Bolivia  \
0           0        0        0       0      0       0        0   
1           0        0        0       0      0       0        0   
2           0        0        0       0      0       0        0   
3           0        0        0       0      0       0        0   
4           0        0        0       0      0       0        0   

   Bosnia and Herzegovina  Botswana  Brazil  Bulgaria  Burkina Faso  Burundi  \
0                    0            0       0         0             0        0   
1                    0            0       0         0             0        0   
2                    0            0       0         0             0        0   
3                    0            0       0         0             0        0   
4                    0            0       0         0             0        0   

   Cambodia  Cameroon  Canada  Central African Republic  Chad  Chile  China  \
0         0         0       0                    0          0      0      0   
1         0         0       0                    0          0      0      0   
2         0         0       0                    0          0      0      0   
3         0         0       0                    0          0      0      0   
4         0         0       0                    0          0      0      0   

   Colombia  Comoros  Costa Rica  Cote d'Ivoire  Croatia  Cuba  Cyprus  \
0         0        0           0              0        0     0       0   
1         0        0           0              0        0     0       0   
2         0        0           0              0        0     0       0   
3         0        0           0              0        0     0       0   
4         0        0           0              0        0     

In [15]:
# 행의 개수 
len(ndf)

1897

In [16]:
newlist = []
for idx in ndf.index :
    if idx <= round(len(ndf)*0.2)-1 :
        newlist += ['1']
    elif idx <= round(len(ndf)*0.4)-1 :
        newlist += ['2']
    elif idx <= round(len(ndf)*0.6)-1 :
        newlist += ['3']
    elif idx <= round(len(ndf)*0.8)-1 :
        newlist += ['4']
    else :
        newlist += ['5']
        
ndf['rank'] = newlist
print(ndf['rank'].unique())

['1' '2' '3' '4' '5']


In [17]:
ndf.head()

Country  Year  Life Ladder  Log GDP per capita  Social support  \
0  Denmark  2005        8.019              10.851           0.972   
1  Denmark  2008        7.971              10.880           0.954   
2  Finland  2020        7.889              10.750           0.962   
3  Finland  2018        7.858              10.783           0.962   
4  Denmark  2007        7.834              10.891           0.954   

   Healthy life expectancy at birth  Freedom to make life choices  Generosity  \
0                69.60                             0.971               -0.127   
1                70.08                             0.970                0.272   
2                72.10                             0.962               -0.116   
3                71.90                             0.938               -0.127   
4                69.92                             0.932                0.240   

   Perceptions of corruption  depressive disorders  schooling  \
0                0.237              196175.189255        12.8   
1                0.248              195682.481706        12.9   
2                0.164              261800.122400        12.4   
3                0.199              256472.440500        12.4   
4                0.206              195599.296492        12.5   

   alcohol disorders  suicide rates  Obesity  Afghanistan  Albania  Algeria  \
0           9.966839       1.385229     7.60            0        0        0   
1          10.426470       1.365589     7.58            0        0        0   
2           6.979488       1.576410    10.93            0        0        0   
3           6.979488       1.576410    10.93            0        0        0   
4          10.896428       1.385044     7.62            0        0        0   

   Angola  Argentina  Armenia  Australia  Austria  Azerbaijan  Bahrain  \
0       0          0        0          0        0           0        0   
1       0          0        0          0        0           0        0   
2       0          0        0          0        0           0        0   
3       0          0        0          0        0           0        0   
4       0          0        0          0        0           0        0   

   Bangladesh  Belarus  Belgium  Belize  Benin  Bhutan  Bolivia  \
0           0        0        0       0      0       0        0   
1           0        0        0       0      0       0        0   
2           0        0        0       0      0       0        0   
3           0        0        0       0      0       0        0   
4           0        0        0       0      0       0        0   

   Bosnia and Herzegovina  Botswana  Brazil  Bulgaria  Burkina Faso  Burundi  \
0                    0            0       0         0             0        0   
1                    0            0       0         0             0        0   
2                    0            0       0         0             0        0   
3                    0            0       0         0             0        0   
4                    0            0       0         0             0        0   

   Cambodia  Cameroon  Canada  Central African Republic  Chad  Chile  China  \
0         0         0       0                    0          0      0      0   
1         0         0       0                    0          0      0      0   
2         0         0       0                    0          0      0      0   
3         0         0       0                    0          0      0      0   
4         0         0       0                    0          0      0      0   

   Colombia  Comoros  Costa Rica  Cote d'Ivoire  Croatia  Cuba  Cyprus  \
0         0        0           0              0        0     0       0   
1         0        0           0              0        0     0       0   
2         0        0           0              0        0     0       0   
3         0        0           0              0        0     0       0   
4         0        0           0              0        0     

In [18]:
# 독립변수과 종속변수 나누기
X = ndf.drop(['Country','Year','Life Ladder','rank'], axis=1)
y = ndf['rank']


In [19]:
# 정규화하기
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

In [20]:
# train 데이터와 test 데이터로 구분
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=4)
print('train data 개수: ', X_train.shape)   
print('test data 개수: ', X_test.shape)     

train data 개수:  (1517, 171)
test data 개수:  (380, 171)


In [25]:
###### 1. KNN 분류 모형 ######
##### KNN 분류 모형 - sklearn 사용
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_hat = knn.predict(X_test)
print(y_hat[0:10])          
print(y_test.values[0:10])  

['1' '1' '5' '4' '5' '3' '4' '4' '4' '2']
['1' '2' '5' '2' '5' '4' '4' '3' '4' '2']


In [22]:
# 혼동행렬
from sklearn import metrics
knn_matrix = metrics.confusion_matrix(y_test, y_hat)
print(knn_matrix)


[[70 10  0  0  0]
 [ 8 48 13  3  0]
 [ 1 11 40 17  3]
 [ 0  4 15 41 17]
 [ 0  0  0 13 66]]


In [23]:
# 성능평가하기
knn_report = metrics.classification_report(y_test, y_hat)
print(knn_report)

              precision    recall  f1-score   support

           1       0.89      0.88      0.88        80
           2       0.66      0.67      0.66        72
           3       0.59      0.56      0.57        72
           4       0.55      0.53      0.54        77
           5       0.77      0.84      0.80        79

    accuracy                           0.70       380
   macro avg       0.69      0.69      0.69       380
weighted avg       0.69      0.70      0.70       380



In [24]:
# 정확도
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print("정확도(Accuracy) :", accuracy_score(y_test,y_hat)) 

정확도(Accuracy) : 0.6973684210526315


In [26]:
###### 2. SVM 분류 모형 ######

from sklearn import svm
svm_model = svm.SVC(kernel='rbf')
svm_model.fit(X_train, y_train)
y_hat= svm_model.predict(X_test)
print(y_hat[0:10])          
print(y_test.values[0:10])  

['1' '1' '5' '2' '5' '4' '4' '4' '4' '2']
['1' '2' '5' '2' '5' '4' '4' '3' '4' '2']


In [27]:
# 혼동행렬
from sklearn import metrics
svm_matrix = metrics.confusion_matrix(y_test,y_hat)
print(svm_matrix)


[[67 12  1  0  0]
 [10 40 15  5  2]
 [ 0  9 33 25  5]
 [ 1  3 13 44 16]
 [ 0  0  0  8 71]]


In [28]:
# 성능평가하기
svm_report = metrics.classification_report(y_test, y_hat)
print(svm_report)

              precision    recall  f1-score   support

           1       0.86      0.84      0.85        80
           2       0.62      0.56      0.59        72
           3       0.53      0.46      0.49        72
           4       0.54      0.57      0.55        77
           5       0.76      0.90      0.82        79

    accuracy                           0.67       380
   macro avg       0.66      0.66      0.66       380
weighted avg       0.67      0.67      0.67       380



In [29]:
# 정확도
print("정확도(Accuracy) : ", accuracy_score(y_test,y_hat))

정확도(Accuracy) :  0.6710526315789473


In [30]:
###### 3. Decision Tree 분류 모형 #####
from sklearn import tree
tree_model = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5)
tree_model.fit(X_train, y_train)
y_hat = tree_model.predict(X_test)
print(y_hat[0:10])           
print(y_test.values[0:10])   

['1' '3' '3' '3' '5' '3' '5' '4' '5' '1']
['1' '2' '5' '2' '5' '4' '4' '3' '4' '2']


In [31]:
# 혼동행렬
tree_matrix = metrics.confusion_matrix(y_test, y_hat)
print(tree_matrix)

[[54 17  8  0  1]
 [ 9 34 27  1  1]
 [ 0 13 42 12  5]
 [ 1  4 25 22 25]
 [ 0  0  3  7 69]]


In [32]:
# 성능평가하기
tree_report = metrics.classification_report(y_test, y_hat)
print(tree_report)

              precision    recall  f1-score   support

           1       0.84      0.68      0.75        80
           2       0.50      0.47      0.49        72
           3       0.40      0.58      0.47        72
           4       0.52      0.29      0.37        77
           5       0.68      0.87      0.77        79

    accuracy                           0.58       380
   macro avg       0.59      0.58      0.57       380
weighted avg       0.60      0.58      0.57       380



In [33]:
# 정확도
print("정확도(Accuracy) : ", accuracy_score(y_test,y_hat)) 

정확도(Accuracy) :  0.5815789473684211


In [36]:
###### 4. 로지스틱회귀분석 ######

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=4)
lr.fit(X_train,y_train)
y_hat = lr.predict(X_test)
print(y_hat[:10])           
print(y_test.values[:10])   


['1' '1' '5' '2' '5' '3' '4' '4' '4' '2']
['1' '2' '5' '2' '5' '4' '4' '3' '4' '2']


C:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [35]:
# 혼동행렬
from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_test,y_hat)
print(confmat)

[[68 11  1  0  0]
 [ 8 44 14  6  0]
 [ 1  6 42 20  3]
 [ 0  1 14 48 14]
 [ 0  0  2  8 69]]


In [37]:
# 성능평가하기
logistic_report = metrics.classification_report(y_test, y_hat)
print(logistic_report)


              precision    recall  f1-score   support

           1       0.88      0.85      0.87        80
           2       0.71      0.61      0.66        72
           3       0.58      0.58      0.58        72
           4       0.59      0.62      0.60        77
           5       0.80      0.87      0.84        79

    accuracy                           0.71       380
   macro avg       0.71      0.71      0.71       380
weighted avg       0.71      0.71      0.71       380



In [38]:
# 정확도
print("정확도(Accuracy) : ", accuracy_score(y_test,y_hat))

정확도(Accuracy) :  0.7131578947368421


In [40]:
###### 5. GradientBoostingClassifier 모델 ######

from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier()
clf.fit(X_train,y_train)
y_hat = clf.predict(X_test)
print(y_hat[:10])      
print(y_test[:10].values)

['1' '2' '5' '3' '5' '3' '4' '4' '4' '2']
['1' '2' '5' '2' '5' '4' '4' '3' '4' '2']


In [41]:
# 혼동행렬
from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_test,y_hat)
print(confmat)

[[70 10  0  0  0]
 [ 8 45 18  1  0]
 [ 0  6 41 20  5]
 [ 0  1 13 52 11]
 [ 0  0  2  9 68]]


In [42]:
# 성능평가하기
GBC_report = metrics.classification_report(y_test, y_hat)
print(GBC_report)

              precision    recall  f1-score   support

           1       0.90      0.88      0.89        80
           2       0.73      0.62      0.67        72
           3       0.55      0.57      0.56        72
           4       0.63      0.68      0.65        77
           5       0.81      0.86      0.83        79

    accuracy                           0.73       380
   macro avg       0.72      0.72      0.72       380
weighted avg       0.73      0.73      0.73       380



In [43]:
#정확도
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print("정확도(Accuracy) :", accuracy_score(y_test,y_hat)) 

정확도(Accuracy) : 0.7263157894736842
